---
- hosts: eos
  connection: network_cli
  gather_facts: no
  become_method: enable

  vars:
    ansible_network_os: eos
    parsers:
    - command: show version
      parser: parsers/eos/show_version.yaml
    - command: show version | json
      parser: parsers/eos/show_version_json.yaml

  roles:
    - ~/RHWork/network-engine

  tasks:
    - name: run and parse commands
      cli:
        command: "{{ item.command }}"
        parser: "{{ item.parser }}"
      loop: "{{ parsers }}"

