---
- hosts: localhost
  connection: local

  #vars:
  #  - ansible_network_os: ios

  roles:
    - ~/RHWork/network-engine

  tasks:
  - name: Parse from contents and generate json structure
      text_parser:
        file: parsers/ios/show_interfaces.yaml
        contents: "{{ lookup('file', 'output/ios/show_interfaces.txt') }}"
      register: result
      vars:
        - ansible_network_os: ios

    - debug: var=result

    #- name: Run and Parse command
    #  cli:
    #    command: show interface
    #    parser: parsers/ios/show_interfaces.yaml
    #    engine: text_parser
